@echo off
cd cfgdayz
del arma2oaserver.RPT
del HiveExt.log
del mpStatistics.log
cd BattlEye
del addbackpackcargo.log
del addmagazinecargo.log
del addweaponcargo.log
del createvehicle.log
del deleteVehicle.log
del mpeventhandler.log
del publicvariable.log
del publicvariableval.log
del publicvariablevar.log
del remoteexec.log
del setdamage.log
del setpos.log
del setvariable.log
del setvariableval.log
del scripts.log
echo All log-files deleted!